### ISSUE TITLE
[Anti-adblock] egy.best

### ISSUE THREAD

**Issue by YASINEDr** [NanoAdblocker/NanoFilters#373]
### URLs where this issue occurs (Required)
https://egy.best

### Screenshots (Required)

![screenshot-egy best-2019 07 17-13-33-16](https://user-images.githubusercontent.com/34688076/61375742-8962ea80-a897-11e9-9d38-55878bba0317.png)

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment]
@okiehsch Not sure if it's hard. The message imply that it's hard though.

**Comment by okiehsch** [comment]
I already checked that site yesterday, the problem I see is that if click any film I get
![image](https://user-images.githubusercontent.com/16838044/61422144-b7354700-a90a-11e9-94b9-daaf8673f31d.png)

Which is caused by Chromes popup blocker and there is really nothing that can be done about that with uBO as far as I can see.

**Comment by okiehsch** [comment]
Does
````
egy.best##+js(set-constant.js, _AdBlock, noopFunc)
egy.best##+js(setTimeout-defuser.js, '0x)
````
work without breaking anything?

**Comment by smed79** [comment]
tested, working.

**Comment by okiehsch** [comment]
Fixed.
