### ISSUE TITLE
[Anti-adblock] laptopmag.com

### ISSUE THREAD

**Issue by dividedby** [NanoAdblocker/NanoFilters#514]
### URLs where this issue occurs (Required)
https://www.laptopmag.com

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/64715420/84435206-0c4f0b00-abf7-11ea-916c-2b544964dd8d.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/64715420/84435810-086fb880-abf8-11ea-8d18-59d181197e93.png)

### Describe the issue (Optional if obvious)
laptopmag.com redirects to laptopmag.com/cc.html if ad block is detected

### Reproduction Steps (Optional if trivial)

Navigate to laptopmag.com

### Anything else you believe to be useful (Optional)
Adding this rule makes it so the anti adblock isn't tripped
`www.laptopmag.com vanilla.futurecdn.net * noop`

#### Environment (Required)

- Operating System and Version: Windows 10 1809
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/64715420/84436065-71efc700-abf8-11ea-9e9b-ea396db3a2f8.png)

#### Your custom filters (Required if you have any)
None related

#### Your other extensions (Required if you have any)
None related

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/84452348-dae43880-ac12-11ea-9cbf-4736767d41b5.png)

**Comment by dividedby** [comment]
Third party script blocking needs to be enabled to reproduce. Adblock is detected when you block scripts from vanilla.futurecdn.net. For example this crude filter: `||vanilla.futurecdn.net$script,domain=www.laptopmag.com,redirect=noop.js`
bypasses the anti adblock but doesn't allow some of the images to load.

![image](https://user-images.githubusercontent.com/64715420/84454499-454fa580-ac20-11ea-8e23-e3e06f8979cd.png)

Personally I'm good using the rule I shared above but was trying to find a way to create a rule to bypass the anti adblock for anyone else.
`www.laptopmag.com vanilla.futurecdn.net * noop`

**Comment by dividedby** [comment]
I see that this rule was added to the uBlock annoyances but it doesn't seem to work for me after enabling the filter list or adding the rule manually.
`laptopmag.com##+js(aopr, _sp_.mms.startMsg)`

**Comment by llacb47** [comment]
Yep, because that filter is for soft anti-adblock- hence its presence in annoyances list.

![image](https://user-images.githubusercontent.com/16567977/84457389-8354c580-ac30-11ea-9658-b64107fe9740.png)
(screenshot from sister site)

The sites work fine on default filters. Since you are not on defaults, you are expected to resolve any issues. 
If you want to continue blocking a `futurecdn` script without triggering this anti-adb add this: 

`||futurecdn.net^*gb.js|$script,domain=bikeperfect.com|creativebloq.com|cyclingnews.com|digitalcameraworld.com|guitarplayer.com|guitarworld.com|laptopmag.com|livescience.com|musicradar.com|pcgamer.com|realhomes.com|space.com|techradar.com|tomshardware.com|toptenreviews.com|whathifi.com,redirect=noopjs`

**Comment by jspenguin2017** [comment]
I can't reproduce any anti-adblock (soft nor hard) on Nano default. 
`laptopmag.com##+js(aopr, _sp_.mms.startMsg)` is already in the Nano base filter. 

If you decide to use a non-default setup (such as third party script blocking), you are expected to fix issues you face yourself.
